### ISSUE TITLE
（测试版）1.下载个别光影包时pcl概率崩溃（复现一次）2.按版本搜索光影包时，点进单独光影包出现所选版本不匹配或无快捷下载3.标签混乱

### ISSUE THREAD

**Issue by Aspy1** [allMagicNB/PCL2#22]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.下载页面中 点击个别光影包概率弹出
![08c46a6ca8607fe86268a2af600335e6](https://github.com/user-attachments/assets/843fbf88-2975-4938-880f-9cc3d499ea10)
然后pcl关闭
2.按版本检索时（搜索1.12为例）
![image](https://github.com/user-attachments/assets/b6777ee8-a5ba-4fd0-bd90-2623f2ee3998)
但是：
![image](https://github.com/user-attachments/assets/a3794d05-06c5-47ce-89b4-ecd8f6083771)
pcl显示我选择的版本为1.21
问题2 为部分整合包出现 其余整合包表现为不弹出“选择的版本为”选项 如：
![image](https://github.com/user-attachments/assets/4f2ae575-2318-4730-b135-6d959c7414c7)
也就是没有快捷下载
3.对于单独光影包：
![image](https://github.com/user-attachments/assets/f0f9d90b-9682-4f7c-839b-09d7c6a64512)
![image](https://github.com/user-attachments/assets/2939e512-aa4d-4a46-8c50-8aa57650c16e)
同时具有多种 性能影响 标签

### 重现步骤

1.进入光影包下载页面，任意点击某光影包有概率触发（疑似标签非常多的光影包触发概率大）
2.先选择版本 再下载光影包 
3.这个进去就能看到吧（）

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/17088124/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17088126/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17088127/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17088128/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17088129/Log4.txt)

**Comment by allMagicNB** [comment]
已解决

**Comment by Aspy1** [comment]
但是话又说回来了 这个能要活跃橙吗（
![24129F04F6ACE0607796C2C58B1C8D21](https://github.com/user-attachments/assets/00bfe308-c392-4970-b45f-940060385562)

**Comment by allMagicNB** [comment]
> 但是话又说回来了 这个能要活跃橙吗（
> ![24129F04F6ACE0607796C2C58B1C8D21](https://github.com/user-attachments/assets/00bfe308-c392-4970-b45f-940060385562)
> 

龙猫不让有相关功能（
